### ISSUE TITLE
"Window is dedicated" error from 'gameoflife-animate'

### ISSUE THREAD

**Issue by jguenther** [Lindydancer/gameoflife#1]
This seems to happen if I use `gameoflife-screensaver-mode` and when manually calling `gameoflife-animate`. Seems to be related to dedicated windows, in my case from [`company-box`](https://github.com/sebastiencs/company-box) and [`lsp-mode`](https://github.com/emacs-lsp/lsp-mode) / [`lsp-ui-mode`](https://github.com/emacs-lsp/lsp-ui)

note that when I got this error, I had 1 frame with 1 window open displaying a plain file buffer. no other windows were visible at the time. I think these buffers are used for internals of lsp-mode / company-mode, for showing tooltip popups etc.

example from `gameoflife-screensaver-mode` (after idling a while):
```
Error running timer ‘gameoflife-animate-with-limit’: (error "Window is dedicated to ‘ *company-box-5doc*’")
```

another example from `gameoflife-animate` called manually from helm M-x:
```
helm-M-x-execute-command: Window is dedicated to ‘ *lsp-ui-doc-1*’
```

let me know if you need any further info though, this is a cool package and can't wait to use it :)

**Comment by Lindydancer** [comment]
Hi!

Thanks for the bug report. It should be relatively straight forward to fix
this (just skip the deprecated windows).

I will try to find some time to fix it (which might not be as straight
forward)...

Thanks!

    -- Anders

**Comment by Lindydancer** [comment]
Hi again!

I investigated the hooks that I had at my disposal and found
change-major-mode-after-body-hook which is called before all normal mode
hooks.

Can you give the attached (rough) patch a try?

One drawback is that it makes it hander to install this package
manually, but I guess that very few people do that nowadays. (I haven't
updated the documentation yet.)

    -- Anders

**Comment by Lindydancer** [comment]
Sorry, wrong person and wrong project.

    -- Anders

**Comment by jguenther** [comment]
Sorry for the delay--

I'd be happy to try it out no problem, I can't seem to find a patch though 😕 

edit: ah I missed your last message, no worries 😄

**Comment by Lindydancer** [comment]
Hi!

I haven't had time to look at the problem yet. I accidentally sent you a
patch for another project I was working on, sorry about the noise.

I'll let you know when I've fixed the problem.

    -- Anders

**Comment by Lindydancer** [comment]
Hi!

Today, I found some time for this. I've pushed a new version that excludes dedicated windows.

Thanks for reporting this!

    -- Anders
